name: my_project
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  http_parser: ^4.0.2
  json_annotation: ^4.8.1
  

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  very_good_analysis: ^5.0.0
